server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: reliable-server
  zipkin:
    base-url: http://localhost:8001
  sleuth:
      sampler:
        percentage: 1.0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

feign:
  hystrix:
    enabled: true #默认feign是不开启hystrix的，所以要设置该配置为true

management:
  security:
    enabled: false

info:
  version: "1.0-SNAPSHOT"
  app:
   name: "reliable-server"
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.reliable.message.client.server.domain

#reliable.message.reliableMessageProducer
#reliable.message.producerGroup
#reliable:
#  message:
#    reliableMessageProducer: true
#    producerGroup: ${spring.application.name}














